### PR TITLE
Use monospace font in <textarea>

### PR DESCRIPTION
**Pull request by matiassingers**
PS: should probably split these inline styles out into a separate stylesheet at some point.

### CODE REVIEW

**Comment by davestevens** [comment]
Thanks!

**Comment by matiassingers** [comment]
I was about to build something exactly like this a couple of months back when I was building some Slack commands - this is really great!

**Comment by davestevens** [comment]
I was creating a deployment script and spent more time figuring out the styling! Glad it came in handy for someone else! I'm gonna add some info for building it locally because I'd forgotten what I'd set up for it.

Is there anything you would add? I've not been using Slack for a couple of months but I've just started using it again for some projects.

**Comment by matiassingers** [comment]
@davestevens perhaps support for the new `response_types` (`in_channel` + `ephemeral`): https://api.slack.com/slash-commands

**Pull request merged**
